// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $API_city_ from "./routes/API/[city].ts";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Emojis from "./islands/Emojis.tsx";
import * as $WeatherIsland from "./islands/WeatherIsland.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/API/[city].ts": $API_city_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Emojis.tsx": $Emojis,
    "./islands/WeatherIsland.tsx": $WeatherIsland,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
